[build]
  command = "AWS_LAMBDA_FUNCTION_NAME=trickpuppeteer npm run build"
  publish = "dist"

[[headers]]
  for = "/*"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
